version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
before_build:
- ps: >-
    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);  

    Set-Location $rootLocation | Out-Null;  

    nuget restore;  

    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);  

    Set-Location $rootLocation\ChatbotScriptUpdater | Out-Null;  

    ..\Build\appveyor.before-build.ps1;  

    Set-Location $rootLocation | Out-Null;  

build:
  verbosity: minimal
before_package:
- ps: >-
    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);  

    Set-Location $rootLocation\ChatbotScriptUpdater | Out-Null;  

    ..\Build\appveyor.before-package.ps1;  

    Set-Location $rootLocation | Out-Null;  

after_build:
- ps: >-
    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);  

    Set-Location "$rootLocation\ChatbotScriptUpdater" | Out-Null;  

    ..\Build\appveyor.after-build.ps1;  

    Set-Location $rootLocation | Out-Null;  

artifacts:
- path: '**\chatbotscriptupdater-v*.zip'
  name: Zips
before_deploy:
- ps: >-
    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);  

    Set-Location $rootLocation\ChatbotScriptUpdater | Out-Null;  

    ..\Build\appveyor.before-deployment.ps1;  

    Set-Location $rootLocation | Out-Null;  

deploy:
- provider: GitHub
  auth_token:
    secure: Es5XTlIJiCiCFJHGDOA09AGFVZQL0jIWtUuPp4+m7MBcfeoVGbWQP2jYU3oSL5bw
  artifact: Zips
  force_update: true
  on:
    CI_DEPLOY_GITHUB: True
after_deploy:
- ps: >-
    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);  

    Set-Location $rootLocation\ChatbotScriptUpdater | Out-Null;   

    ..\Build\appveyor.after-deployment.ps1;  

    Set-Location $rootLocation | Out-Null;  

